[package]
name = "ol-smoke-test"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies]
anyhow = "1.0.52"
async-trait = "0.1.42"
bcs = "0.1.2"
proptest = "1.0.0"
tokio = { version = "1.8.1", features = ["full"] }
walkdir = "2.3.1"
reqwest = { version = "0.11.2", features = ["json"] }

diem-config = { path = "../../config" }
diem-crypto = { path = "../../crates/diem-crypto" }
diem-events-fetcher = { path = "../../diem-move/diem-events-fetcher" }
diem-experimental-framework-releases = { path = "../../diem-move/diem-framework/experimental/releases" }
diem-framework = { path = "../../diem-move/diem-framework" }
diem-framework-releases = { path = "../../diem-move/diem-framework/DPN/releases" }
diem-json-rpc-types = { path = "../../json-rpc/types" }
diem-sdk = { path = "../../sdk" }
diem-rest-client = { path = "../../crates/diem-rest-client" }
diem-temppath = { path = "../../crates/diem-temppath" }
diem-transaction-builder = { path = "../../sdk/transaction-builder" }
diem-transaction-replay = { path = "../../diem-move/transaction-replay" }
move-command-line-common = { git = "https://github.com/0LNetworkCommunity/move-0L", rev = "94e1039c9fdf1472c2c7775de43135d28dafc955" }
move-ir-compiler = { git = "https://github.com/0LNetworkCommunity/move-0L", rev = "94e1039c9fdf1472c2c7775de43135d28dafc955" }
move-stdlib = { git = "https://github.com/0LNetworkCommunity/move-0L", rev = "94e1039c9fdf1472c2c7775de43135d28dafc955" }
diem-types = { path = "../../types" }
forge = { path = "../../testsuite/forge" }
diem-workspace-hack = { version = "0.1", path = "../../crates/diem-workspace-hack" }

[dev-dependencies]
base64 = "0.13.0"
hex = "0.4.3"
once_cell = "1.7.2"
rand = "0.8.3"
regex = "1.4.3"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
serde_yaml = "0.8.17"
futures = "0.3.12"
backup-cli = { path = "../../storage/backup/backup-cli" }
debug-interface = { path = "../../crates/debug-interface" }
generate-key = { path = "../../config/generate-key" }
diem-genesis-tool = {path = "../../config/management/genesis", features = ["testing"] }
diem-global-constants = { path = "../../config/global-constants" }
diem-infallible = { path = "../../crates/diem-infallible" }
diem-json-rpc = { path = "../../json-rpc" }
diem-json-rpc-types = { path = "../../json-rpc/types" }
diem-key-manager = { path = "../../secure/key-manager" }
diem-logger = { path = "../../crates/diem-logger" }
diem-management = { path = "../../config/management", features = ["testing"] }
diem-operational-tool = {path = "../../config/management/operational", features = ["testing"] }
diem-secure-storage = { path = "../../secure/storage", features = ["testing"] }
diem-time-service = { path = "../../crates/diem-time-service", features = ["testing"] }
diem-vault-client = { path = "../../secure/storage/vault", features = ["fuzzing"] }
diem-validator-interface = { path = "../../diem-move/diem-validator-interface" }
diem-wallet = { path = "../../crates/diem-wallet", version = "0.1.0" }
diem-writeset-generator = { path = "../../diem-move/writeset-transaction-generator" }
diem-transaction-builder = { path = "../../sdk/transaction-builder" }
ol-types = { path = "../../ol/types"}
smoke-test = { path = "../../testsuite/smoke-test", features = ["ol-smoke-test"] }
